### PR TITLE
fix: HAL-05 Unhandled Errors

### LINKED ISSUE #1192: Price-feeder: (HAL-05) UNHANDLED ERRORS - INFORMATIONAL
## Summary
There are a few instances where error handling has not been implemented for functions that might return an error.

## Proposal
We recommend that the appropriate error checking be implemented to avoid unexpected crashes.

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by khoerling**
- additionally handles okx & kraken

## Description

closes: #1192 

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ x ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] added appropriate labels to the PR
- [ x ] targeted the correct branch (see [PR Targeting](https://github.com/umee-network/umee/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ x ] reviewed "Files changed" and left comments if necessary
- [ x ] confirmed all CI checks have passed

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items._

I have...

- [ x ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ x ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ x ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

File: price-feeder/oracle/provider/binance.go [hunk 1]
```diff
@@ -360,7 +360,10 @@ func (p *BinanceProvider) handleWebSocketMsgs(ctx context.Context) {
 // the websocket server does not receive a pong frame back from the connection
 // within a 10 minute period, the connection will be disconnected.
 func (p *BinanceProvider) reconnect() error {
-	p.wsClient.Close()
+	err := p.wsClient.Close()
+	if err != nil {
+		return fmt.Errorf("error closing binance websocket connection: %s", err)
```
Comment (robert-zaremba) [inline price-feeder/oracle/provider/binance.go:365]:
```suggestion
		return fmt.Errorf("error closing binance websocket connection: %w", err)
```

File: price-feeder/oracle/provider/coinbase.go [hunk 2]
```diff
@@ -480,7 +480,10 @@ func (p *CoinbaseProvider) resetReconnectTimer() {
 // 3. Expect a 'pong' as a response. If the response message is not received within
 // N seconds, please raise an error or reconnect.
 func (p *CoinbaseProvider) reconnect() error {
-	p.wsClient.Close()
+	err := p.wsClient.Close()
+	if err != nil {
+		return fmt.Errorf("error closing Coinbase websocket connection: %s", err)
```
Comment (robert-zaremba) [inline price-feeder/oracle/provider/coinbase.go:485]:
```suggestion
		return fmt.Errorf("error closing Coinbase websocket connection: %w", err)
```

File: price-feeder/oracle/provider/gate.go [hunk 3]
```diff
@@ -546,7 +546,10 @@ func (p *GateProvider) resetReconnectTimer() {
 // 3. Expect a 'pong' as a response. If the response message is not received within
 // N seconds, please raise an error or reconnect.
 func (p *GateProvider) reconnect() error {
-	p.wsClient.Close()
+	err := p.wsClient.Close()
+	if err != nil {
+		return fmt.Errorf("error closing Gate websocket connection: %s", err)
```
Comment (robert-zaremba) [inline price-feeder/oracle/provider/gate.go:551]:
```suggestion
		return fmt.Errorf("error closing Gate websocket connection: %w", err)
```

File: price-feeder/oracle/provider/huobi.go [hunk 4]
```diff
@@ -382,7 +382,10 @@ func (p *HuobiProvider) setCandlePair(candle HuobiCandle) {
 
 // reconnect closes the last WS connection and create a new one.
 func (p *HuobiProvider) reconnect() error {
-	p.wsClient.Close()
+	err := p.wsClient.Close()
+	if err != nil {
+		return fmt.Errorf("error closing Huobi websocket connection: %s", err)
```
Comment (robert-zaremba) [inline price-feeder/oracle/provider/huobi.go:387]:
```suggestion
		return fmt.Errorf("error closing Huobi websocket connection: %w", err)
```

Comment (robert-zaremba) [reply price-feeder/oracle/provider/huobi.go:387]: In other places below as well.

**Review by robert-zaremba — COMMENTED** [review]
I would prefer that we create a function to wrap that connection errors, or a base error to wrap the post error, eg:
```
ErrProviderConnection          = sdkerrors.Register(ModuleName, 17, "Provider connection")
```

**Comment by adamewozniak** [comment]
> I would prefer that we create a function to wrap that connection errors, or a base error to wrap the post error, eg:
> 
> ```
> ErrProviderConnection          = sdkerrors.Register(ModuleName, 17, "Provider connection")
> ```

Agreed ^
Also @khoerling when this error is returned what happens?

**Comment by khoerling** [comment]
> > I would prefer that we create a function to wrap that connection errors, or a base error to wrap the post error, eg:
> > ```
> > ErrProviderConnection          = sdkerrors.Register(ModuleName, 17, "Provider connection")
> > ```
> 
> Agreed ^ Also @khoerling when this error is returned what happens?

Excellent question-- on error, `keepReconnecting()` is called and a reconnect is tried up to `keepReconnecting`, currently set to 3.

**Comment by khoerling** [comment]
I _believe_ this is what was being asked for, still calibrating and learning.  I've got to fix the types issue, can squash/rebase into a single commit and merge after figuring that out.

p.s.
Still getting 100% setup with localized testing, etc...

File: price-feeder/oracle/provider/coinbase.go [hunk 5]
```diff
@@ -480,7 +481,10 @@ func (p *CoinbaseProvider) resetReconnectTimer() {
 // 3. Expect a 'pong' as a response. If the response message is not received within
 // N seconds, please raise an error or reconnect.
 func (p *CoinbaseProvider) reconnect() error {
-	p.wsClient.Close()
+	err := p.wsClient.Close()
+	if err != nil {
+		return sdkerrors.Wrap(types.ErrProviderConnection, fmt.Errorf("error closing Coinbase websocket %w", err))
```
Comment (robert-zaremba) [inline price-feeder/oracle/provider/coinbase.go:486]: 1. You can use a shortcut: `types.ErrProviderConnection.Wrapf("error closing Coinbase websocket %v", err)`. Note, here we use `%v`, instead of `%w`, because `Wrapf` is using `fmt.Sprintf` under the hood.
2. I have always a dilemma if we should 
    * wrap a source error (`err`) on top of our base error (this way we loose `err` structure and  `ErrProviderConnection` is the causer (parent error) - this is the way how the SDK operates.
    * or to wrap the connection error on top of a message: (the alternative I've presented earlier): 
    
        ```go
        func connectionErr(provider string) error { 
          return fmt.Errorf("error closing %s websocket: %w", provider,  err)
        }
        ```

Since here we are returning a generic connection error, then I'm more inclined with the first approach. So... if you agree, then please use the shourtcut.

**Review by robert-zaremba — COMMENTED** [review]
* Still need to improve errors wrapping
* tests are failing

File: x/oracle/types/errors.go [hunk 6]
```diff
@@ -25,4 +25,5 @@ var (
 	ErrNegativeOrZeroRate    = sdkerrors.Register(ModuleName, 14, "invalid exchange rate; should be positive")
 	ErrExistingPrevote       = sdkerrors.Register(ModuleName, 15, "prevote already submitted for this voting period")
 	ErrBallotNotSorted       = sdkerrors.Register(ModuleName, 16, "ballot must be sorted before this operation")
+	ErrProviderConnection    = sdkerrors.Register(ModuleName, 17, "provider connection")
```
Comment (adamewozniak) [inline x/oracle/types/errors.go:28]: Need to remove this

**Review by adamewozniak — APPROVED** [review]
lgtm, please have robert check again :^) 

tests gotta pass though

**Review by robert-zaremba — APPROVED** [review]
lgtm

**Review by khoerling — COMMENTED** [review]
One more approval, please-- grazi  @robert-zaremba

File: price-feeder/oracle/provider/coinbase.go (hunk 5 above)
Comment (adamewozniak) [reply price-feeder/oracle/provider/coinbase.go]: Resolved in a29979fd52212c4c2f214c3cfb84eaccb9aac414

**Comment by adamewozniak** [comment]
> One more approval, please-- grazi @robert-zaremba err... there's a conversation needing to be resolved according to github

I hit resolve on the remaining comment -- but @khoerling please sign your commits before this gets merged 🚀

**Comment by khoerling** [comment]
Absolutely, went ahead and signed every commit  #yolo
